language: node_js
sudo: required
env:
  global:
  - secure: X2CB2PKUOcavASFsvRe420ahdhheb35oHwzTchcdud+Vitrz16EUuFozCgY7yNdtIIBzkkpIaw+ZbkyQxK16o3R3LiygyEuAt/o2WtcDHm1ABh1Y89TwuqrWQBnaPoAV4LEBntlfL9YFWAafNansCinIcY4hqND6FvRxUowvUkV+aZ30Ao32hOG6+NnpnkiN3dtjLibnwSVPasGRfUmpg2fpU9c6+pW16axUDwp5iclRGJs6u3+J2g6CgdaJCwrguM9dgmMkFGXtNjkegwd75G6JlvK+jOeSOACaY51VJPQj54rEB5z1jZ2Mhy3GshAQ9zOO2I6cpaylTtIN8S+7LbpZvONuAjyXjcWTURuZsEnpWr5HeCRqftkXlG1Wr/AJscvn/6r0jjcmbnT3C/vJxgfKAuqvv8CFXXQBeV0Bqz+HvAdo7eoAIpLrsPSFrDxiR2E8zcyqhJh7lWs8YFcwzGltwYEk0QMGknHCeENh3dKrWgYOdOnOn4dhzx69/1GHN33FTIBgDSu07ySzTJzwdQNhPqxxeMaB00ABtG45euOzMzaB7lBjmXfsswDfTev6/kJSb2PkQrTOyfTXWj1x16USfyP70z6lo3yYz2llM9TjoxP7eYIjYcMFYnPb7kucCAR4xQdyP7E3SSpVdwVI6/ZPJQTpNmnqG6DN7SCowDY=
  - secure: NaXWB2XRp27jL8tKF9iQ7DkjXMDqUOL4I0T54H8EEyGR73KELONAY2mUCiriW6WD/uvGMs24AOHgw6RQLPpWggrqFDq5/2hzW/KF1U4HelgfAfZGDMu6OVP6o3AXGcDxZUcFDboq5rmljxjrNVrXMwUD48Of9JhKfYiv+ESISi5+1a9SW3w1QilIZdjuJqPPVEBuldLL6cGB/OtA6c9NZGvXCRHA7oxAMNmDGKnnlJ30/tz4L0uZNxJwmtKz/u/PNigWAFhexXfEy0D5zkrWa83eGFD54Ks4HHDImD0RCbt3nJ8ot1Mg/zLSjICKtY8DY6YiJ2QJ1AfAzhJwE6N+X3Vw98viD4oCe4G4TvXB6AMN6agnPYboHZecM0bIGqWSudC3z4uFNJPaiIiHN83Gy0IP49gLOwkt6wz9CuZAqekXpshUBPxbaZYrFLUlkl6p/MbrpZnuIAnJwV+MA2XBqtGhs5eD1IaCyr1nDidVWzDdbRP+HJupPKo/KPgdb8rb4cS395SPTf2aJyLw01Ufmz6AQCv8fEXjRMDQcZurmKJsrYcX1UWdYLlsYLi8aSm0i7gDc/jDcwDq4rM2tZOmen//5KdBIvyqYCubJBX4sh2KWUDzmWfMW6pT6Wboiv1ird/TN4OAt/w8orb/3Uod3pTBsVuePBw5uC24YjPDOrU=
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- stable
os:
- linux
services:
- docker
before_install:
# set up a docker image with emscripten ready to go
- docker run -dit --name emscripten -v $(pwd):/project trzeci/emscripten:sdk-incoming-64bit bash
script:
# install the library dependencies
- ./ci-install.sh
# run the build script on the docker image
- docker exec -it emscripten bash -c 'cd /project; ./build.sh'
# run tests locally
- npm run test
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
